[default]
log_level = 2
daemon_stderr = "./goproxy-vps.log"

[[http2]]
listen = ":443"
server_name = ["phus.lu", "grafana.phus.lu"]
proxy_auth_method = "pam"
proxy_fallback = "http://127.0.0.1:80"

[[http2]]
listen = ":443"
server_name = ["jp.phus.lu"]
sign_rsa_autocert = true
parent_proxy = "https://c1.phus.lu:31150/"
#proxy_auth_method = "pam"

[[http2]]
listen = ":443"
server_name = ["tw.phus.lu"]
parent_proxy = "http://127.0.0.1:8080"
proxy_auth_method = "pam"

[http]
listen = ":9000"
parent_proxy = "https://c1.phus.lu:31150"
