[default]
log_level = 2
daemon_stderr = "/dev/null"

[[http2]]
listen = ":443"
server_name = ["phus.lu", "perf.phus.lu"]
proxy_auth_method = "pam"
proxy_fallback = "http://127.0.0.1:80"
keyfile = "/home/phuslu/drive/pem/phus.lu.pem"
certfile = "/home/phuslu/drive/pem/phus.lu.pem"

[[http2]]
listen = ":443"
server_name = ["proxy.phus.lu"]
parent_proxy = "http://127.0.0.1:8080"
proxy_auth_method = "pam"
