[default]
log_level = 2

[[http2]]
listen = ":443"
server_name = ["phus.lu"]
proxy_fallback = "http://127.0.0.1:80"

[[http2]]
listen = ":443"
server_name = ["proxy.phus.lu"]
parent_proxy = "http://127.0.0.1:8080"
proxy_auth_method = "pam"
